spring.application.name=tuturno

# --- CONEXIÓN DOCKER ---
spring.datasource.url=jdbc:postgresql://localhost:5432/tuturno_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA ---
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true
